package merlin.model.raw;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import merlin.model.raw.Reminder;
import merlin.model.raw.Meal;
import merlin.model.raw.ImageHolder;

import merlin.model.raw.ReminderDao;
import merlin.model.raw.MealDao;
import merlin.model.raw.ImageHolderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reminderDaoConfig;
    private final DaoConfig mealDaoConfig;
    private final DaoConfig imageHolderDaoConfig;

    private final ReminderDao reminderDao;
    private final MealDao mealDao;
    private final ImageHolderDao imageHolderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reminderDaoConfig = daoConfigMap.get(ReminderDao.class).clone();
        reminderDaoConfig.initIdentityScope(type);

        mealDaoConfig = daoConfigMap.get(MealDao.class).clone();
        mealDaoConfig.initIdentityScope(type);

        imageHolderDaoConfig = daoConfigMap.get(ImageHolderDao.class).clone();
        imageHolderDaoConfig.initIdentityScope(type);

        reminderDao = new ReminderDao(reminderDaoConfig, this);
        mealDao = new MealDao(mealDaoConfig, this);
        imageHolderDao = new ImageHolderDao(imageHolderDaoConfig, this);

        registerDao(Reminder.class, reminderDao);
        registerDao(Meal.class, mealDao);
        registerDao(ImageHolder.class, imageHolderDao);
    }
    
    public void clear() {
        reminderDaoConfig.getIdentityScope().clear();
        mealDaoConfig.getIdentityScope().clear();
        imageHolderDaoConfig.getIdentityScope().clear();
    }

    public ReminderDao getReminderDao() {
        return reminderDao;
    }

    public MealDao getMealDao() {
        return mealDao;
    }

    public ImageHolderDao getImageHolderDao() {
        return imageHolderDao;
    }

}
