package merlin.model.raw;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import merlin.model.raw.BaseReminder;

import merlin.model.raw.BaseReminderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseReminderDaoConfig;

    private final BaseReminderDao baseReminderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseReminderDaoConfig = daoConfigMap.get(BaseReminderDao.class).clone();
        baseReminderDaoConfig.initIdentityScope(type);

        baseReminderDao = new BaseReminderDao(baseReminderDaoConfig, this);

        registerDao(BaseReminder.class, baseReminderDao);
    }
    
    public void clear() {
        baseReminderDaoConfig.getIdentityScope().clear();
    }

    public BaseReminderDao getBaseReminderDao() {
        return baseReminderDao;
    }

}
