package merlin.model.raw;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import merlin.model.raw.BaseReminder;
import merlin.model.raw.BaseMeal;
import merlin.model.raw.BaseImageHolder;

import merlin.model.raw.BaseReminderDao;
import merlin.model.raw.BaseMealDao;
import merlin.model.raw.BaseImageHolderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baseReminderDaoConfig;
    private final DaoConfig baseMealDaoConfig;
    private final DaoConfig baseImageHolderDaoConfig;

    private final BaseReminderDao baseReminderDao;
    private final BaseMealDao baseMealDao;
    private final BaseImageHolderDao baseImageHolderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baseReminderDaoConfig = daoConfigMap.get(BaseReminderDao.class).clone();
        baseReminderDaoConfig.initIdentityScope(type);

        baseMealDaoConfig = daoConfigMap.get(BaseMealDao.class).clone();
        baseMealDaoConfig.initIdentityScope(type);

        baseImageHolderDaoConfig = daoConfigMap.get(BaseImageHolderDao.class).clone();
        baseImageHolderDaoConfig.initIdentityScope(type);

        baseReminderDao = new BaseReminderDao(baseReminderDaoConfig, this);
        baseMealDao = new BaseMealDao(baseMealDaoConfig, this);
        baseImageHolderDao = new BaseImageHolderDao(baseImageHolderDaoConfig, this);

        registerDao(BaseReminder.class, baseReminderDao);
        registerDao(BaseMeal.class, baseMealDao);
        registerDao(BaseImageHolder.class, baseImageHolderDao);
    }
    
    public void clear() {
        baseReminderDaoConfig.getIdentityScope().clear();
        baseMealDaoConfig.getIdentityScope().clear();
        baseImageHolderDaoConfig.getIdentityScope().clear();
    }

    public BaseReminderDao getBaseReminderDao() {
        return baseReminderDao;
    }

    public BaseMealDao getBaseMealDao() {
        return baseMealDao;
    }

    public BaseImageHolderDao getBaseImageHolderDao() {
        return baseImageHolderDao;
    }

}
